/*!40101 SET NAMES binary*/;
CREATE TABLE `x$statement_analysis`(
`query` int,
`db` int,
`full_scan` int,
`exec_count` int,
`err_count` int,
`warn_count` int,
`total_latency` int,
`max_latency` int,
`avg_latency` int,
`lock_latency` int,
`rows_sent` int,
`rows_sent_avg` int,
`rows_examined` int,
`rows_examined_avg` int,
`rows_affected` int,
`rows_affected_avg` int,
`tmp_tables` int,
`tmp_disk_tables` int,
`rows_sorted` int,
`sort_merge_passes` int,
`digest` int,
`first_seen` int,
`last_seen` int
)ENGINE=MyISAM;
