/*!40101 SET NAMES binary*/;
CREATE TABLE `innodb_lock_waits`(
`wait_started` int,
`wait_age` int,
`wait_age_secs` int,
`locked_table` int,
`locked_index` int,
`locked_type` int,
`waiting_trx_id` int,
`waiting_trx_started` int,
`waiting_trx_age` int,
`waiting_trx_rows_locked` int,
`waiting_trx_rows_modified` int,
`waiting_pid` int,
`waiting_query` int,
`waiting_lock_id` int,
`waiting_lock_mode` int,
`blocking_trx_id` int,
`blocking_pid` int,
`blocking_query` int,
`blocking_lock_id` int,
`blocking_lock_mode` int,
`blocking_trx_started` int,
`blocking_trx_age` int,
`blocking_trx_rows_locked` int,
`blocking_trx_rows_modified` int,
`sql_kill_blocking_query` int,
`sql_kill_blocking_connection` int
)ENGINE=MyISAM;
