/*!40101 SET NAMES binary*/;
CREATE TABLE `x$processlist`(
`thd_id` int,
`conn_id` int,
`user` int,
`db` int,
`command` int,
`state` int,
`time` int,
`current_statement` int,
`statement_latency` int,
`progress` int,
`lock_latency` int,
`rows_examined` int,
`rows_sent` int,
`rows_affected` int,
`tmp_tables` int,
`tmp_disk_tables` int,
`full_scan` int,
`last_statement` int,
`last_statement_latency` int,
`current_memory` int,
`last_wait` int,
`last_wait_latency` int,
`source` int,
`trx_latency` int,
`trx_state` int,
`trx_autocommit` int,
`pid` int,
`program_name` int
)ENGINE=MyISAM;
